debug

diff --git a/termux-url-opener b/termux-url-opener
--- a/termux-url-opener
+++ b/termux-url-opener
@@ -17,24 +17,24 @@ chmod 777 $WD_AYD/update.sh
 
 upd()
 {
-    if [[ $(git -C $WD_AYD fetch --dry-run 2>&1 | wc -l) -gt 0 ]]; then
-        echo -e $GREEN "Update found !" $NC
-        #wait $DYT_PID
-        ls -l $WD_AYD/update.sh
-        echo -e $BLUE $WD_AYD/update.sh $NC
-        exec $WD_AYD/update.sh $ARGS
+  if [[ $(git -C $WD_AYD fetch --dry-run 2>&1 | wc -l) -gt 0 ]]; then
+    echo -e $GREEN "Update found !" $NC
+    #wait $DYT_PID
+    ls -l $WD_AYD/update.sh
+    echo -e $BLUE $WD_AYD/update.sh $NC
+    exec $WD_AYD/update.sh $ARGS
 
-        sleep 10
-        exit 1
-    fi
-    echo -e $YELLOW "Ayd it's up to date" $NC
-    sleep 5
+    sleep 10
+    exit 1
+  fi
+  echo -e $YELLOW "Ayd it's up to date" $NC
+  sleep 5
 
-    if [ $NARGS -eq 0 ]; then
-        echo -e $BLUE "Instalation complete." $NC
-        sleep 10
-        exit 0
-    fi
+  if [ $NARGS -eq 0 ]; then
+    echo -e $BLUE "Instalation complete." $NC
+    sleep 10
+    exit 0
+  fi
 }
 
 upd
@@ -48,40 +48,40 @@ pip install --upgrade youtube-dl 1>/dev/null 2>>log.txt
 
 if [[ $1 =~ ^.*youtu.*$ ]]; then
 
-    echo -e ${YELLOW} "Youtube-dl" ${NC}
-    TMP_DIR="$(mktemp -dt musica-dl.XXXXXX)"
-    OUT_DIR="/storage/emulated/0/Music/musica-dl"
-    CONFIG="${HOME}/.config/musica-dl"
+  echo -e ${YELLOW} "Youtube-dl" ${NC}
+  TMP_DIR="$(mktemp -dt musica-dl.XXXXXX)"
+  OUT_DIR="/storage/emulated/0/Music/musica-dl"
+  CONFIG="${HOME}/.config/musica-dl"
 
-    mkdir "${TMP_DIR}"/raw "${TMP_DIR}"/cooked
+  mkdir "${TMP_DIR}"/raw "${TMP_DIR}"/cooked
 
-    youtube-dl \
-        --ignore-errors \
-        --write-thumbnail \
-        --download-archive descargados-miniatura.txt \
-        --skip-download \
-        --output "${TMP_DIR}/cooked/%(title)s" \
-        -- "$@" \
-        1>/dev/null &
+  youtube-dl \
+    --ignore-errors \
+    --write-thumbnail \
+    --download-archive descargados-miniatura.txt \
+    --skip-download \
+    --output "${TMP_DIR}/cooked/%(title)s" \
+    -- "$@" \
+    1>/dev/null &
 
 
-    youtube-dl \
-        --ignore-errors \
-        --download-archive descargados.txt \
-        --format 'bestaudio' \
-        --output "${TMP_DIR}/raw/%(title)s" \
-        -- "$@"
+  youtube-dl \
+    --ignore-errors \
+    --download-archive descargados.txt \
+    --format 'bestaudio' \
+    --output "${TMP_DIR}/raw/%(title)s" \
+    -- "$@"
 
-    for file in "${TMP_DIR}/raw/"*; do
-        ffmpeg \
-            -hide_banner \
-            -i "$file" \
-            -codec:a libmp3lame \
-            -qscale:a 2 \
-            -vn \
-            -map_metadata -1 \
-            "${TMP_DIR}/cooked/${file##*/}.mp3"
-        done
+  for file in "${TMP_DIR}/raw/"*; do
+    ffmpeg \
+      -hide_banner \
+      -i "$file" \
+      -codec:a libmp3lame \
+      -qscale:a 2 \
+      -vn \
+      -map_metadata -1 \
+      "${TMP_DIR}/cooked/${file##*/}.mp3"
+    done
 
 #       if command -v eyeD3 >/dev/null; then
 #               eyeD3 --remove-all "${TMP_DIR}"/cooked/*.mp3
@@ -91,9 +91,9 @@ mkdir -p "${OUT_DIR}"
 cp -f "${TMP_DIR}"/cooked/* "${OUT_DIR}"
 cd "${TMP_DIR}/cooked"
 for file in * ; do
-    echo $file
-    mkdir -p ${OUT_DIR}/${file%%.*}
-    cp ${file} ${OUT_DIR}/${file%%.*}/${file}
+  echo $file
+  mkdir -p ${OUT_DIR}/${file%%.*}
+  cp ${file} ${OUT_DIR}/${file%%.*}/${file}
 done
 
 rm -rf "${TMP_DIR}"
@@ -101,7 +101,7 @@ rm -rf "${TMP_DIR}"
 sleep 20
 
 elif [[ $1 =~ ^.*nourlselected.*$ ]]; then
-    echo "ERROR1"
+  echo "ERROR1"
 else
-    echo Unhandled URL type: $1
+  echo Unhandled URL type: $1
 fi
